name: RentalCar
options:
  bundleIdPrefix: com.alex.myapp
  deploymentTarget:
    iOS: '17.0'
  generateEmptyDirectories: true

configs:
  Debug: {}
  Release: {}

targets:
  App:
    type: application
    platform: iOS
    sources:
      - path: App
      - path: Domain
      - path: Data
      - path: Infrastructure
      - path: Presentation
      - path: Utilities
      - path: Utilities/Extensions
      - path: Utilities/Properties
      - path: Utilities/ViewModifiers

    resources:
      - path: Resources
        excludes: ["**/*.md", "**/.DS_Store"]
        
    settings:
      base:
        INFO_PLIST_FILE: App/Info.plist
        SWIFT_VERSION: 6.0
        DEFINES_MODULE: NO
        GENERATE_INFOPLIST_FILE: YES

      debug:
        CFBundleVersion: "1"
        CFBundleShortVersionString: "1.0.0-debug"

      release:
        CFBundleVersion: "42"
        CFBundleShortVersionString: "1.0.0"
